### ISSUE TITLE
error looking up "davidlee"

### ISSUE THREAD

**Issue by shea256** [namesystem/resolver#44]
When I lookup "davidlee" on the onename-hosted resolver (http://resolver.onename.com/v1/users/davidlee), I get the following:

```json
{
  "error": "Not found"
}
```

But if I lookup "davidlee" on Namechain (http://namecha.in/name/u/davidlee) all the data shows up.

My guess is there's an orphaned next pointer that's not being handled correctly.

**Comment by muneeb-ali** [comment]
Fixed in ccadb55f55c08371ea91f740c111fa45d577a65c

See http://resolver.onename.com/v1/users/davidlee
